# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: cheng_jjj@163.com
brand: ccc
headline: 今天的每一分努力，明天都会把最好的给你
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: cheng_jjj@163.com
phone: 13698007061

# Tracking
googleAnalitycsID: UA-83933844-1

